user:
  email:
    max_length: 255
    VALID_EMAIL_REGEX: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'
digits:
  digit_0: 0
  digit_1: 1
  digit_6: 6
  digit_21: 21
  digit_0: 0
  digit_1: 1
format_time: "%H:%M - %m/%d/%Y"
user_url: https://secure.gravatar.com/avatar/
user_bets_path: /user_bets
sql:
  sql_find_period: "updated_at BETWEEN ? AND ?"
arr_content_bets: ["Team Home Win", "Tow Team Draw", "Team Guest Win", "Score: 0-0", "Score: 0-1", "Score: 1-0", "Score: 1-1", "Score other"]
dashboard_path: /vi/admin_manager
admin_app_name: ["Managerment App -", "Welcome to Admin worksheet"]
